name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: Europe/Stockholm # Set timezone
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          config_order: base.header, isocalendar, languages

      - name: 🦑 Personal metrics (right)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.anilist.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga             # Display both animes and mangas
          plugin_anilist_sections: favorites, characters  # Display only favorites and characters sections
          plugin_anilist_limit: 2                         # Limit to 2 entry per section (characters section excluded)
          plugin_anilist_shuffle: yes                     # Shuffle data for more varied outputs
          plugin_anilist_user: .user.login                # Use same username as GitHub login
          plugin_anilist_limit_characters: 22             # Limit to 22 characters in characters section

      - name: 🦑 Personal metrics (bottom)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""    
          plugin_achievements: yes
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: compact   
          
